// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm } from "emdash";

export interface PageContentMarketingHeroV1Block {
  _type: "marketing_hero";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "eyebrow"?: string | null;
  "headline": string;
  "subheadline"?: string | null;
  "primary_cta_label"?: string | null;
  "primary_cta_url"?: string | null;
  "secondary_cta_label"?: string | null;
  "secondary_cta_url"?: string | null;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
  "centered"?: boolean | null;
  "specs"?: { "icon": "zap" | "database" | "code" | "cloud" | "rocket" | "lock" | "globe"; "label": string }[] | null;
}

export type PageContentMarketingHeroBlock = PageContentMarketingHeroV1Block;

export interface PageContentMarketingFeaturesV1Block {
  _type: "marketing_features";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline": string;
  "subheadline"?: string | null;
  "features": { "icon": "zap" | "shield" | "users" | "chart" | "code" | "globe" | "heart" | "star" | "check" | "lock" | "clock" | "cloud" | "rocket" | "palette" | "plug" | "swap" | "lifebuoy" | "wrench" | "book" | "video" | "gift"; "title": string; "description": string }[];
}

export type PageContentMarketingFeaturesBlock = PageContentMarketingFeaturesV1Block;

export interface PageContentMarketingTestimonialsV1Block {
  _type: "marketing_testimonials";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline"?: string | null;
  "testimonials": { "quote": string; "author": string; "role"?: string | null; "company"?: string | null; "avatar"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null }[];
}

export type PageContentMarketingTestimonialsBlock = PageContentMarketingTestimonialsV1Block;

export interface PageContentMarketingPricingV1Block {
  _type: "marketing_pricing";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline"?: string | null;
  "plans": { "name": string; "price": string; "period"?: string | null; "description"?: string | null; "features"?: string | null; "cta_label": string; "cta_url": string; "highlighted"?: boolean | null }[];
}

export type PageContentMarketingPricingBlock = PageContentMarketingPricingV1Block;

export interface PageContentMarketingFaqV1Block {
  _type: "marketing_faq";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline"?: string | null;
  "items": { "question": string; "answer": string }[];
}

export type PageContentMarketingFaqBlock = PageContentMarketingFaqV1Block;

export interface PageContentSiteTutorialsV1Block {
  _type: "site_tutorials";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline"?: string | null;
  "subheadline"?: string | null;
  "limit"?: number | null;
  "featured_only"?: boolean | null;
  "show_filters"?: boolean | null;
  "section_cta_label"?: string | null;
  "section_cta_url"?: string | null;
}

export type PageContentSiteTutorialsBlock = PageContentSiteTutorialsV1Block;

export interface PageContentSiteVideosV1Block {
  _type: "site_videos";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline"?: string | null;
  "subheadline"?: string | null;
  "limit"?: number | null;
  "featured_only"?: boolean | null;
  "spotlight"?: boolean | null;
  "section_cta_label"?: string | null;
  "section_cta_url"?: string | null;
}

export type PageContentSiteVideosBlock = PageContentSiteVideosV1Block;

export interface PageContentSiteResourcesV1Block {
  _type: "site_resources";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline"?: string | null;
  "subheadline"?: string | null;
  "kind"?: "all" | "theme" | "plugin" | null;
  "price"?: "all" | "free" | "paid" | null;
  "limit"?: number | null;
  "featured_only"?: boolean | null;
  "show_filters"?: boolean | null;
  "section_cta_label"?: string | null;
  "section_cta_url"?: string | null;
}

export type PageContentSiteResourcesBlock = PageContentSiteResourcesV1Block;

export interface PageContentSiteServicesV1Block {
  _type: "site_services";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline"?: string | null;
  "subheadline"?: string | null;
  "limit"?: number | null;
  "featured_only"?: boolean | null;
  "section_cta_label"?: string | null;
  "section_cta_url"?: string | null;
}

export type PageContentSiteServicesBlock = PageContentSiteServicesV1Block;

export interface PageContentSiteCtaV1Block {
  _type: "site_cta";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline": string;
  "subheadline"?: string | null;
  "primary_cta_label"?: string | null;
  "primary_cta_url"?: string | null;
  "secondary_cta_label"?: string | null;
  "secondary_cta_url"?: string | null;
  "style"?: "gradient" | "plain" | null;
}

export type PageContentSiteCtaBlock = PageContentSiteCtaV1Block;

export interface PageContentSiteContactV1Block {
  _type: "site_contact";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline"?: string | null;
  "subheadline"?: string | null;
  "methods": { "icon": "mail" | "lifebuoy" | "youtube" | "github" | "x" | "globe" | "book"; "title": string; "description"?: string | null; "label": string; "url": string }[];
}

export type PageContentSiteContactBlock = PageContentSiteContactV1Block;

export interface PageContentContactFormV1Block {
  _type: "contact_form";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline"?: string | null;
  "subheadline"?: string | null;
  "form": string;
}

export type PageContentContactFormBlock = PageContentContactFormV1Block;

export type PageContentBlock = PageContentMarketingHeroBlock | PageContentMarketingFeaturesBlock | PageContentMarketingTestimonialsBlock | PageContentMarketingPricingBlock | PageContentMarketingFaqBlock | PageContentSiteTutorialsBlock | PageContentSiteVideosBlock | PageContentSiteResourcesBlock | PageContentSiteServicesBlock | PageContentSiteCtaBlock | PageContentSiteContactBlock | PageContentContactFormBlock;

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PageContentBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Tutorial {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  summary?: string;
  url: string;
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  topic?: "getting-started" | "themes" | "plugins" | "deployment" | "content-modeling" | "migration" | "review";
  level?: "beginner" | "intermediate" | "advanced";
  featured?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Video {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  youtube_url: string;
  summary?: string;
  duration?: string;
  article_url?: string;
  thumbnail?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  featured?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Resource {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  kind: "theme" | "plugin";
  price_type: "free" | "paid";
  price?: string;
  summary?: string;
  url: string;
  demo_url?: string;
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  cta_label?: string;
  featured?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Service {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  summary: string;
  icon?: "zap" | "shield" | "users" | "chart" | "code" | "globe" | "heart" | "star" | "check" | "lock" | "clock" | "cloud" | "rocket" | "palette" | "plug" | "swap" | "lifebuoy" | "wrench" | "book" | "video" | "gift";
  price_label?: string;
  features?: string;
  cta_label?: string;
  cta_url?: string;
  featured?: boolean;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    pages: Page;
    tutorials: Tutorial;
    videos: Video;
    resources: Resource;
    services: Service;
  }
}