// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface PageContentMarketingHeroV1Block {
  _type: "marketing_hero";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "eyebrow"?: string | null;
  "headline": string;
  "subheadline"?: string | null;
  "primary_cta_label"?: string | null;
  "primary_cta_url"?: string | null;
  "secondary_cta_label"?: string | null;
  "secondary_cta_url"?: string | null;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
  "centered"?: boolean | null;
  "specs"?: { "icon": "zap" | "database" | "code" | "cloud" | "rocket" | "lock" | "globe"; "label": string }[] | null;
}

export type PageContentMarketingHeroBlock = PageContentMarketingHeroV1Block;

export interface PageContentMarketingFeaturesV1Block {
  _type: "marketing_features";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline": string;
  "subheadline"?: string | null;
  "features": { "icon": "zap" | "shield" | "users" | "chart" | "code" | "globe" | "heart" | "star" | "check" | "lock" | "clock" | "cloud" | "rocket" | "palette" | "plug" | "swap" | "lifebuoy" | "wrench" | "book" | "video" | "gift"; "title": string; "description": string }[];
}

export type PageContentMarketingFeaturesBlock = PageContentMarketingFeaturesV1Block;

export interface PageContentMarketingTestimonialsV1Block {
  _type: "marketing_testimonials";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline"?: string | null;
  "testimonials": { "quote": string; "author": string; "role"?: string | null; "company"?: string | null; "avatar"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null }[];
}

export type PageContentMarketingTestimonialsBlock = PageContentMarketingTestimonialsV1Block;

export interface PageContentMarketingPricingV1Block {
  _type: "marketing_pricing";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline"?: string | null;
  "plans": { "name": string; "price": string; "period"?: string | null; "description"?: string | null; "features"?: string | null; "cta_label": string; "cta_url": string; "highlighted"?: boolean | null }[];
}

export type PageContentMarketingPricingBlock = PageContentMarketingPricingV1Block;

export interface PageContentMarketingFaqV1Block {
  _type: "marketing_faq";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline"?: string | null;
  "items": { "question": string; "answer": string }[];
}

export type PageContentMarketingFaqBlock = PageContentMarketingFaqV1Block;

export interface PageContentSiteTutorialsV1Block {
  _type: "site_tutorials";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline"?: string | null;
  "subheadline"?: string | null;
  "limit"?: number | null;
  "featured_only"?: boolean | null;
  "show_filters"?: boolean | null;
  "section_cta_label"?: string | null;
  "section_cta_url"?: string | null;
}

export type PageContentSiteTutorialsBlock = PageContentSiteTutorialsV1Block;

export interface PageContentSiteVideosV1Block {
  _type: "site_videos";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline"?: string | null;
  "subheadline"?: string | null;
  "limit"?: number | null;
  "featured_only"?: boolean | null;
  "spotlight"?: boolean | null;
  "section_cta_label"?: string | null;
  "section_cta_url"?: string | null;
}

export type PageContentSiteVideosBlock = PageContentSiteVideosV1Block;

export interface PageContentSiteResourcesV1Block {
  _type: "site_resources";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline"?: string | null;
  "subheadline"?: string | null;
  "kind"?: "all" | "theme" | "plugin" | null;
  "price"?: "all" | "free" | "paid" | null;
  "limit"?: number | null;
  "featured_only"?: boolean | null;
  "show_filters"?: boolean | null;
  "section_cta_label"?: string | null;
  "section_cta_url"?: string | null;
}

export type PageContentSiteResourcesBlock = PageContentSiteResourcesV1Block;

export interface PageContentSiteServicesV1Block {
  _type: "site_services";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline"?: string | null;
  "subheadline"?: string | null;
  "limit"?: number | null;
  "featured_only"?: boolean | null;
  "section_cta_label"?: string | null;
  "section_cta_url"?: string | null;
}

export type PageContentSiteServicesBlock = PageContentSiteServicesV1Block;

export interface PageContentSiteCtaV1Block {
  _type: "site_cta";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline": string;
  "subheadline"?: string | null;
  "primary_cta_label"?: string | null;
  "primary_cta_url"?: string | null;
  "secondary_cta_label"?: string | null;
  "secondary_cta_url"?: string | null;
  "style"?: "gradient" | "plain" | null;
}

export type PageContentSiteCtaBlock = PageContentSiteCtaV1Block;

export interface PageContentSiteContactV1Block {
  _type: "site_contact";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline"?: string | null;
  "subheadline"?: string | null;
  "methods": { "icon": "mail" | "lifebuoy" | "youtube" | "github" | "x" | "globe" | "book"; "title": string; "description"?: string | null; "label": string; "url": string }[];
}

export type PageContentSiteContactBlock = PageContentSiteContactV1Block;

export interface PageContentContactFormV1Block {
  _type: "contact_form";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline"?: string | null;
  "subheadline"?: string | null;
  "form": string;
}

export type PageContentContactFormBlock = PageContentContactFormV1Block;

export interface PageContentWidgetAccordionV1Block {
  _type: "widget_accordion";
  _version: 1;
  _key: string;
  "heading"?: string | null;
  "items"?: { "title": string; "body": string }[] | null;
}

export type PageContentWidgetAccordionBlock = PageContentWidgetAccordionV1Block;

export interface PageContentWidgetButtonV1Block {
  _type: "widget_button";
  _version: 1;
  _key: string;
  "label": string;
  "url": string;
  "icon"?: "arrow-right" | "arrow-up-right" | "download" | "play" | "check" | "star" | "info" | "rocket" | "book" | "github" | "mail" | "terminal" | null;
  "variant"?: "solid" | "outline" | null;
  "align"?: "left" | "center" | "right" | null;
  "new_tab"?: boolean | null;
}

export type PageContentWidgetButtonBlock = PageContentWidgetButtonV1Block;

export interface PageContentWidgetChecklistV1Block {
  _type: "widget_checklist";
  _version: 1;
  _key: string;
  "title"?: string | null;
  "items"?: { "text": string }[] | null;
}

export type PageContentWidgetChecklistBlock = PageContentWidgetChecklistV1Block;

export interface PageContentWidgetEmbedV1Block {
  _type: "widget_embed";
  _version: 1;
  _key: string;
  "url": string;
  "title": string;
  "aspect"?: "16:9" | "4:3" | "1:1" | "9:16" | null;
}

export type PageContentWidgetEmbedBlock = PageContentWidgetEmbedV1Block;

export interface PageContentWidgetFactsV1Block {
  _type: "widget_facts";
  _version: 1;
  _key: string;
  "title"?: string | null;
  "items"?: { "label": string; "value": string }[] | null;
}

export type PageContentWidgetFactsBlock = PageContentWidgetFactsV1Block;

export interface PageContentWidgetLatestPostsV1Block {
  _type: "widget_latest_posts";
  _version: 1;
  _key: string;
  "heading"?: string | null;
  "collection"?: string | null;
  "limit"?: number | null;
  "exclude_current"?: boolean | null;
}

export type PageContentWidgetLatestPostsBlock = PageContentWidgetLatestPostsV1Block;

export interface PageContentWidgetNoticeV1Block {
  _type: "widget_notice";
  _version: 1;
  _key: string;
  "kind": "info" | "success" | "warning" | "danger";
  "title"?: string | null;
  "body": PortableTextBlock[];
}

export type PageContentWidgetNoticeBlock = PageContentWidgetNoticeV1Block;

export interface PageContentWidgetProductV1Block {
  _type: "widget_product";
  _version: 1;
  _key: string;
  "name": string;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
  "rating"?: number | null;
  "description"?: string | null;
  "pros"?: { "text": string }[] | null;
  "cons"?: { "text": string }[] | null;
  "price"?: string | null;
  "url"?: string | null;
  "cta_label"?: string | null;
}

export type PageContentWidgetProductBlock = PageContentWidgetProductV1Block;

export interface PageContentWidgetProseV1Block {
  _type: "widget_prose";
  _version: 1;
  _key: string;
  "body": PortableTextBlock[];
}

export type PageContentWidgetProseBlock = PageContentWidgetProseV1Block;

export interface PageContentWidgetQuoteV1Block {
  _type: "widget_quote";
  _version: 1;
  _key: string;
  "quote": string;
  "attribution"?: string | null;
  "role"?: string | null;
}

export type PageContentWidgetQuoteBlock = PageContentWidgetQuoteV1Block;

export interface PageContentWidgetSeriesV1Block {
  _type: "widget_series";
  _version: 1;
  _key: string;
  "title"?: string | null;
  "items"?: { "label": string; "url": string }[] | null;
}

export type PageContentWidgetSeriesBlock = PageContentWidgetSeriesV1Block;

export interface PageContentWidgetTabsV1Block {
  _type: "widget_tabs";
  _version: 1;
  _key: string;
  "items"?: { "label": string; "body": string }[] | null;
}

export type PageContentWidgetTabsBlock = PageContentWidgetTabsV1Block;

export interface PageContentWidgetTocV1Block {
  _type: "widget_toc";
  _version: 1;
  _key: string;
  "title"?: string | null;
}

export type PageContentWidgetTocBlock = PageContentWidgetTocV1Block;

export interface PageContentWidgetYoutubeV1Block {
  _type: "widget_youtube";
  _version: 1;
  _key: string;
  "url": string;
  "title": string;
  "caption"?: string | null;
}

export type PageContentWidgetYoutubeBlock = PageContentWidgetYoutubeV1Block;

export interface PageContentSitePostsV1Block {
  _type: "site_posts";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline"?: string | null;
  "subheadline"?: string | null;
  "limit"?: number | null;
  "featured_only"?: boolean | null;
  "section_cta_label"?: string | null;
  "section_cta_url"?: string | null;
}

export type PageContentSitePostsBlock = PageContentSitePostsV1Block;

export interface PageContentWidgetStepsV1Block {
  _type: "widget_steps";
  _version: 1;
  _key: string;
  "title"?: string | null;
  "items"?: { "title": string; "body"?: string | null }[] | null;
}

export type PageContentWidgetStepsBlock = PageContentWidgetStepsV1Block;

export interface PageContentWidgetImageV1Block {
  _type: "widget_image";
  _version: 1;
  _key: string;
  "image": { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  "caption"?: string | null;
  "wide"?: boolean | null;
}

export type PageContentWidgetImageBlock = PageContentWidgetImageV1Block;

export interface PageContentWidgetCodeV1Block {
  _type: "widget_code";
  _version: 1;
  _key: string;
  "language"?: "plaintext" | "bash" | "typescript" | "javascript" | "json" | "html" | "css" | "yaml" | "sql" | "python" | null;
  "filename"?: string | null;
  "code": string;
}

export type PageContentWidgetCodeBlock = PageContentWidgetCodeV1Block;

export interface PageContentWidgetCardsV1Block {
  _type: "widget_cards";
  _version: 1;
  _key: string;
  "title"?: string | null;
  "items"?: { "icon"?: "arrow-right" | "arrow-up-right" | "download" | "play" | "check" | "star" | "info" | "rocket" | "book" | "github" | "mail" | "terminal" | null; "title": string; "url": string; "description"?: string | null }[] | null;
}

export type PageContentWidgetCardsBlock = PageContentWidgetCardsV1Block;

export interface PageContentWidgetDividerV1Block {
  _type: "widget_divider";
  _version: 1;
  _key: string;
  "style"?: "line" | "dots" | "space" | null;
}

export type PageContentWidgetDividerBlock = PageContentWidgetDividerV1Block;

export type PageContentBlock = PageContentMarketingHeroBlock | PageContentMarketingFeaturesBlock | PageContentMarketingTestimonialsBlock | PageContentMarketingPricingBlock | PageContentMarketingFaqBlock | PageContentSiteTutorialsBlock | PageContentSiteVideosBlock | PageContentSiteResourcesBlock | PageContentSiteServicesBlock | PageContentSiteCtaBlock | PageContentSiteContactBlock | PageContentContactFormBlock | PageContentWidgetAccordionBlock | PageContentWidgetButtonBlock | PageContentWidgetChecklistBlock | PageContentWidgetEmbedBlock | PageContentWidgetFactsBlock | PageContentWidgetLatestPostsBlock | PageContentWidgetNoticeBlock | PageContentWidgetProductBlock | PageContentWidgetProseBlock | PageContentWidgetQuoteBlock | PageContentWidgetSeriesBlock | PageContentWidgetTabsBlock | PageContentWidgetTocBlock | PageContentWidgetYoutubeBlock | PageContentSitePostsBlock | PageContentWidgetStepsBlock | PageContentWidgetImageBlock | PageContentWidgetCodeBlock | PageContentWidgetCardsBlock | PageContentWidgetDividerBlock;

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PageContentBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface PostBodyWidgetAccordionV1Block {
  _type: "widget_accordion";
  _version: 1;
  _key: string;
  "heading"?: string | null;
  "items"?: { "title": string; "body": string }[] | null;
}

export type PostBodyWidgetAccordionBlock = PostBodyWidgetAccordionV1Block;

export interface PostBodyWidgetButtonV1Block {
  _type: "widget_button";
  _version: 1;
  _key: string;
  "label": string;
  "url": string;
  "icon"?: "arrow-right" | "arrow-up-right" | "download" | "play" | "check" | "star" | "info" | "rocket" | "book" | "github" | "mail" | "terminal" | null;
  "variant"?: "solid" | "outline" | null;
  "align"?: "left" | "center" | "right" | null;
  "new_tab"?: boolean | null;
}

export type PostBodyWidgetButtonBlock = PostBodyWidgetButtonV1Block;

export interface PostBodyWidgetChecklistV1Block {
  _type: "widget_checklist";
  _version: 1;
  _key: string;
  "title"?: string | null;
  "items"?: { "text": string }[] | null;
}

export type PostBodyWidgetChecklistBlock = PostBodyWidgetChecklistV1Block;

export interface PostBodyWidgetEmbedV1Block {
  _type: "widget_embed";
  _version: 1;
  _key: string;
  "url": string;
  "title": string;
  "aspect"?: "16:9" | "4:3" | "1:1" | "9:16" | null;
}

export type PostBodyWidgetEmbedBlock = PostBodyWidgetEmbedV1Block;

export interface PostBodyWidgetFactsV1Block {
  _type: "widget_facts";
  _version: 1;
  _key: string;
  "title"?: string | null;
  "items"?: { "label": string; "value": string }[] | null;
}

export type PostBodyWidgetFactsBlock = PostBodyWidgetFactsV1Block;

export interface PostBodyWidgetLatestPostsV1Block {
  _type: "widget_latest_posts";
  _version: 1;
  _key: string;
  "heading"?: string | null;
  "collection"?: string | null;
  "limit"?: number | null;
  "exclude_current"?: boolean | null;
}

export type PostBodyWidgetLatestPostsBlock = PostBodyWidgetLatestPostsV1Block;

export interface PostBodyWidgetNoticeV1Block {
  _type: "widget_notice";
  _version: 1;
  _key: string;
  "kind": "info" | "success" | "warning" | "danger";
  "title"?: string | null;
  "body": PortableTextBlock[];
}

export type PostBodyWidgetNoticeBlock = PostBodyWidgetNoticeV1Block;

export interface PostBodyWidgetProductV1Block {
  _type: "widget_product";
  _version: 1;
  _key: string;
  "name": string;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
  "rating"?: number | null;
  "description"?: string | null;
  "pros"?: { "text": string }[] | null;
  "cons"?: { "text": string }[] | null;
  "price"?: string | null;
  "url"?: string | null;
  "cta_label"?: string | null;
}

export type PostBodyWidgetProductBlock = PostBodyWidgetProductV1Block;

export interface PostBodyWidgetProseV1Block {
  _type: "widget_prose";
  _version: 1;
  _key: string;
  "body": PortableTextBlock[];
}

export type PostBodyWidgetProseBlock = PostBodyWidgetProseV1Block;

export interface PostBodyWidgetQuoteV1Block {
  _type: "widget_quote";
  _version: 1;
  _key: string;
  "quote": string;
  "attribution"?: string | null;
  "role"?: string | null;
}

export type PostBodyWidgetQuoteBlock = PostBodyWidgetQuoteV1Block;

export interface PostBodyWidgetSeriesV1Block {
  _type: "widget_series";
  _version: 1;
  _key: string;
  "title"?: string | null;
  "items"?: { "label": string; "url": string }[] | null;
}

export type PostBodyWidgetSeriesBlock = PostBodyWidgetSeriesV1Block;

export interface PostBodyWidgetTabsV1Block {
  _type: "widget_tabs";
  _version: 1;
  _key: string;
  "items"?: { "label": string; "body": string }[] | null;
}

export type PostBodyWidgetTabsBlock = PostBodyWidgetTabsV1Block;

export interface PostBodyWidgetTocV1Block {
  _type: "widget_toc";
  _version: 1;
  _key: string;
  "title"?: string | null;
}

export type PostBodyWidgetTocBlock = PostBodyWidgetTocV1Block;

export interface PostBodyWidgetYoutubeV1Block {
  _type: "widget_youtube";
  _version: 1;
  _key: string;
  "url": string;
  "title": string;
  "caption"?: string | null;
}

export type PostBodyWidgetYoutubeBlock = PostBodyWidgetYoutubeV1Block;

export interface PostBodyContactFormV1Block {
  _type: "contact_form";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline"?: string | null;
  "subheadline"?: string | null;
  "form": string;
}

export type PostBodyContactFormBlock = PostBodyContactFormV1Block;

export interface PostBodyWidgetStepsV1Block {
  _type: "widget_steps";
  _version: 1;
  _key: string;
  "title"?: string | null;
  "items"?: { "title": string; "body"?: string | null }[] | null;
}

export type PostBodyWidgetStepsBlock = PostBodyWidgetStepsV1Block;

export interface PostBodyWidgetImageV1Block {
  _type: "widget_image";
  _version: 1;
  _key: string;
  "image": { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  "caption"?: string | null;
  "wide"?: boolean | null;
}

export type PostBodyWidgetImageBlock = PostBodyWidgetImageV1Block;

export interface PostBodyWidgetCodeV1Block {
  _type: "widget_code";
  _version: 1;
  _key: string;
  "language"?: "plaintext" | "bash" | "typescript" | "javascript" | "json" | "html" | "css" | "yaml" | "sql" | "python" | null;
  "filename"?: string | null;
  "code": string;
}

export type PostBodyWidgetCodeBlock = PostBodyWidgetCodeV1Block;

export interface PostBodyWidgetCardsV1Block {
  _type: "widget_cards";
  _version: 1;
  _key: string;
  "title"?: string | null;
  "items"?: { "icon"?: "arrow-right" | "arrow-up-right" | "download" | "play" | "check" | "star" | "info" | "rocket" | "book" | "github" | "mail" | "terminal" | null; "title": string; "url": string; "description"?: string | null }[] | null;
}

export type PostBodyWidgetCardsBlock = PostBodyWidgetCardsV1Block;

export interface PostBodyWidgetDividerV1Block {
  _type: "widget_divider";
  _version: 1;
  _key: string;
  "style"?: "line" | "dots" | "space" | null;
}

export type PostBodyWidgetDividerBlock = PostBodyWidgetDividerV1Block;

export type PostBodyBlock = PostBodyWidgetAccordionBlock | PostBodyWidgetButtonBlock | PostBodyWidgetChecklistBlock | PostBodyWidgetEmbedBlock | PostBodyWidgetFactsBlock | PostBodyWidgetLatestPostsBlock | PostBodyWidgetNoticeBlock | PostBodyWidgetProductBlock | PostBodyWidgetProseBlock | PostBodyWidgetQuoteBlock | PostBodyWidgetSeriesBlock | PostBodyWidgetTabsBlock | PostBodyWidgetTocBlock | PostBodyWidgetYoutubeBlock | PostBodyContactFormBlock | PostBodyWidgetStepsBlock | PostBodyWidgetImageBlock | PostBodyWidgetCodeBlock | PostBodyWidgetCardsBlock | PostBodyWidgetDividerBlock;

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  excerpt?: string;
  cover?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  body?: PostBodyBlock[];
  featured?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Tutorial {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  summary?: string;
  url: string;
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  topic?: "getting-started" | "themes" | "plugins" | "deployment" | "content-modeling" | "migration" | "review";
  level?: "beginner" | "intermediate" | "advanced";
  featured?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Video {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  youtube_url: string;
  summary?: string;
  duration?: string;
  article_url?: string;
  thumbnail?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  featured?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Resource {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  kind: "theme" | "plugin";
  price_type: "free" | "paid";
  price?: string;
  summary?: string;
  url: string;
  demo_url?: string;
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  cta_label?: string;
  featured?: boolean;
  latest_version?: string;
  license?: string;
  package?: string;
  publisher?: string;
  updated?: string;
  changelog?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Service {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  summary: string;
  icon?: "zap" | "shield" | "users" | "chart" | "code" | "globe" | "heart" | "star" | "check" | "lock" | "clock" | "cloud" | "rocket" | "palette" | "plug" | "swap" | "lifebuoy" | "wrench" | "book" | "video" | "gift";
  price_label?: string;
  features?: string;
  cta_label?: string;
  cta_url?: string;
  featured?: boolean;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    pages: Page;
    posts: Post;
    tutorials: Tutorial;
    videos: Video;
    resources: Resource;
    services: Service;
  }
}